name: itemco_test_case
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  itemco_test_case_part:
    path: part

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
